### ISSUE TITLE
Discuss pointblank experiments

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/coding-helpdesk#35]
Discuss pointblank experiments.

## Resources

* Meeting [notes](https://docs.google.com/document/d/1Fxv-KzGDJNssmbrC250pjt1WAhwIBWP_Z07mzN03DMo/edit?usp=sharing).

* The pointblank package:
    * [Website](https://rich-iannone.github.io/pointblank/).
    * ds-incubator  [video](https://github.com/2DegreesInvesting/ds.database/tree/main/03_validate) and [notes](https://github.com/2DegreesInvesting/ds.database/tree/main/03_validate#validating-data-quality).

**Comment by frmfisc** [comment]
Main part of the conversation was the challenge of making html reports created by pointblank to other users. 

Solution: create website for st data repo with [pkgdown](https://pkgdown.r-lib.org/) -> build_site() -> usethis::use_article("toy_pointblank_report") -> populate toy report -> build_site()

Also create a function that opens website (browseURL("docs/index.html"))
