### ISSUE TITLE
Share workflows with R+Git+GitHub via building a mini add-ins package

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/coding-helpdesk#9]
## What is the issue you need help with?

We would like to share our daily workflows. As an excuse we plan to build a min package to host an RStudio addin.

## Resources

* <https://rstudio.github.io/rstudioaddins/#developing-addins>
* <https://github.com/cjyetman/safe.run>

--

@cjyetman @maurolepore @jdhoffa

**Comment by cjyetman** [comment]
https://github.com/cjyetman/safe.run

**Comment by maurolepore** [comment]
It was awesome. Thanks! I look forward to sharing the recordings.
